kind: CronJob
apiVersion: batch/v1beta1
metadata:
  labels:
    app: {{ template "namespace-cleaner.name" . }}
    chart: {{ template "namespace-cleaner.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ template "namespace-cleaner.fullname" . }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ template "namespace-cleaner.fullname" . }}
          containers:
          - name: cleaner
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | toString }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            resources:
              {{- toYaml .Values.cleaner.resources | nindent 14 }}
            env:
            - name: MAX_NAMESPACE_INACTIVE_HOURS
              value: {{default 24 .Values.cleaner.maxAge | quote}}
            - name: NS_WHITELIST
              value: {{ .Values.cleaner.whiteListNamespaces | quote}}
            - name: VSTS_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ template "namespace-cleaner.fullname" . }}
                  key: vsts_pat
          restartPolicy: {{ .Values.cleaner.restartPolicy }}
          activeDeadlineSeconds: {{ .Values.cleaner.activeDeadlineSeconds }}
          imagePullSecrets:
          - name: {{ .Values.cleaner.acrSecretName}}
